server:
  tls:
    enabled: false
    cert_file: /path/to/cert.pem
    key_file: /path/to/key.pem
  port: 8081
  root_directory: ./config/front

global:
  portrange:
    min: 25000
    max: 26000

gameimages:
  - nom: mindustryesgi
    tag: latest
    ports:
      tcp:
        - "6567"
      udp:
        - "6567"
    spec:
      core: 1
      ram: 512